import _ from "lodash";

const PRIMARY_STATS_CATEGORIES = [
  "GP",
  "MIN",
  "FGPCT",
  "FTPCT",
  "TPM",
  "TPPCT",
  "PTS",
  "TREB",
  "AST",
  "STL",
  "BLK",
  "TOV",
];
const SECONDARY_STATS_CATEGORIES = [
  "FGM",
  "FGA",
  "FTM",
  "FTA",
  "TPA",
  "OREB",
  "DREB",
];
const FANTASY_STATS_CATEGORIES = ["ROTO8", "ROTO9", "DFS"];
const ALL_STATS_CATEGORIES = [
  ...PRIMARY_STATS_CATEGORIES,
  ...SECONDARY_STATS_CATEGORIES,
  ...FANTASY_STATS_CATEGORIES,
];

const PRIMARY_STATS_PERIOD = "CURR_SEASON";
const ALL_STATS_PERIODS_MAP = {
  [PRIMARY_STATS_PERIOD]: "2021-22 Season",
  SEASON_2021: "2020-21 Season",
  LAST7: "Last 7 days",
  LAST14: "Last 14 days",
  LAST30: "Last 30 days",
  LAST60: "Last 60 days",
};
const SECONDARY_STATS_PERIODS = _.filter(
  Object.keys(ALL_STATS_PERIODS_MAP),
  PRIMARY_STATS_PERIOD
);
const ALL_STATS_PERIODS = Object.keys(ALL_STATS_PERIODS_MAP);

export {
  PRIMARY_STATS_CATEGORIES,
  SECONDARY_STATS_CATEGORIES,
  FANTASY_STATS_CATEGORIES,
  ALL_STATS_CATEGORIES,
  PRIMARY_STATS_PERIOD,
  ALL_STATS_PERIODS_MAP,
  SECONDARY_STATS_PERIODS,
  ALL_STATS_PERIODS,
};
