const PRIMARY_STATS_CATEGORIES = [
  "GP",
  "MIN",
  "FGPCT",
  "FTPCT",
  "TPM",
  "TPPCT",
  "PTS",
  "TREB",
  "AST",
  "STL",
  "BLK",
  "TOV",
];

const SECONDARY_STATS_CATEGORIES = [
  "FGM",
  "FGA",
  "FTM",
  "FTA",
  "TPA",
  "OREB",
  "DREB",
];

const FANTASY_STATS_CATEGORIES = ["ROTO8", "ROTO9", "DFS"];

const ALL_STATS_CATEGORIES = [
  ...PRIMARY_STATS_CATEGORIES,
  ...SECONDARY_STATS_CATEGORIES,
  ...FANTASY_STATS_CATEGORIES,
];

export {
  PRIMARY_STATS_CATEGORIES,
  SECONDARY_STATS_CATEGORIES,
  FANTASY_STATS_CATEGORIES,
  ALL_STATS_CATEGORIES,
};
