const TEAMS = {
  ATL: { city: "Atlanta", nickname: "Hawks", emoji: "🦅" },
  BOS: { city: "Boston", nickname: "Celtics", emoji: "☘️" },
  BKN: { city: "Brooklyn", nickname: "Nets", emoji: "🐺" },
  CHA: { city: "Charlotte", nickname: "Hornets", emoji: "🐝" },
  CHI: { city: "Chicago", nickname: "Bulls", emoji: "🐂" },
  CLE: { city: "Cleveland", nickname: "Cavaliers", emoji: "⚔" },
  DAL: { city: "Dallas", nickname: "Mavericks", emoji: "🐴" },
  DEN: { city: "Denver", nickname: "Nuggets", emoji: "⛏" },
  DET: { city: "Denver", nickname: "Pistons", emoji: "🚗" },
  GSW: { city: "Golden State", nickname: "Warriors", emoji: "🌉" },
  HOU: { city: "Houston", nickname: "Rockets", emoji: "🚀" },
  IND: { city: "Indiana", nickname: "Pacers", emoji: "🏁" },
  LAC: { city: "Los Angeles", nickname: "Clippers", emoji: "✂️" },
  LAL: { city: "Los Angeles", nickname: "Lakers", emoji: "🌊" },
  MEM: { city: "Memphis", nickname: "Grizzlies", emoji: "🐻" },
  MIA: { city: "Miami", nickname: "Heat", emoji: "🔥" },
  MIL: { city: "Milwaukee", nickname: "Bucks", emoji: "🦌" },
  MIN: { city: "Minnesota", nickname: "Timberwolves", emoji: "🐺" },
  NOP: { city: "New Orleans", nickname: "Pelicans", emoji: "🐦" },
  NYK: { city: "New York", nickname: "Knicks", emoji: "🗽" },
  OKC: { city: "Oklahoma City", nickname: "Thunder", emoji: "🌩" },
  ORL: { city: "Orlando", nickname: "Magic", emoji: "🎩" },
  PHI: { city: "Philadelphia", nickname: "76ers", emoji: "🏛" },
  PHO: { city: "Phoenix", nickname: "Suns", emoji: "☀️" },
  POR: { city: "Portland", nickname: "Trail Blazers", emoji: "👣" },
  SAC: { city: "Sacramento", nickname: "Kings", emoji: "👑" },
  SAS: { city: "San Antonio", nickname: "Spurs", emoji: "⚙" },
  TOR: { city: "Toronto", nickname: "Raptors", emoji: "🦖" },
  UTA: { city: "Utah", nickname: "Jazz", emoji: "🎺" },
  WAS: { city: "Washington", nickname: "Wizards", emoji: "🧙‍♂️" },
};

export { TEAMS };
